server:
  port: 9092

spring:
  application:
    name: bff-service
  #cloud:
  #  loadbalancer:
  #    ribbon:
  #      ConnectTimeout: 3000
  #      ReadTimeout: 5000

client:
  service-url: http://client-service
  #http://localhost:9093

order:
  service-url: http://order-service
  #http://localhost:9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true